version: "2"

formatters:
  enable:
    - goimports

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosec
    - unconvert
    - misspell
    - nilerr
    - noctx
    - errorlint
    - gocritic
  settings:
    gosec:
      excludes:
        - G104
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
