CREATE TABLE menus (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    parent_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    name VARCHAR(32) NOT NULL,
    path VARCHAR(128) NOT NULL DEFAULT '',
    component VARCHAR(128) NOT NULL DEFAULT '',
    icon VARCHAR(64) NOT NULL DEFAULT '',
    sort INT NOT NULL DEFAULT 0,
    type TINYINT NOT NULL DEFAULT 2,
    permission VARCHAR(64) NOT NULL DEFAULT '',
    status TINYINT NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    INDEX idx_parent_id (parent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;