ALTER TABLE users ADD COLUMN phone VARCHAR(32) DEFAULT '';
ALTER TABLE users ADD COLUMN mfa_totp_secret VARCHAR(64) DEFAULT '';
ALTER TABLE users ADD COLUMN mfa_totp_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN mfa_sms_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN mfa_email_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN mfa_backup_codes TEXT DEFAULT '';
