// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "用户登录",
                "responses": {}
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "刷新Token",
                "responses": {}
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "用户注册",
                "responses": {}
            }
        },
        "/api/v1/config-groups": {
            "get": {
                "tags": [
                    "Config"
                ],
                "summary": "配置分组列表",
                "responses": {}
            }
        },
        "/api/v1/configs": {
            "get": {
                "tags": [
                    "Config"
                ],
                "summary": "配置列表",
                "responses": {}
            }
        },
        "/api/v1/dict-types": {
            "get": {
                "tags": [
                    "Dict"
                ],
                "summary": "字典类型列表",
                "responses": {}
            },
            "post": {
                "tags": [
                    "Dict"
                ],
                "summary": "创建字典类型",
                "responses": {}
            }
        },
        "/api/v1/dict-types/:id": {
            "get": {
                "tags": [
                    "Dict"
                ],
                "summary": "字典类型详情",
                "responses": {}
            },
            "put": {
                "tags": [
                    "Dict"
                ],
                "summary": "更新字典类型",
                "responses": {}
            },
            "delete": {
                "tags": [
                    "Dict"
                ],
                "summary": "删除字典类型",
                "responses": {}
            }
        },
        "/api/v1/dict-types/:id/entries": {
            "get": {
                "tags": [
                    "Dict"
                ],
                "summary": "字典条目列表（按类型）",
                "responses": {}
            },
            "post": {
                "tags": [
                    "Dict"
                ],
                "summary": "创建字典条目",
                "responses": {}
            }
        },
        "/api/v1/dict-types/:id/entries/:entryId": {
            "put": {
                "tags": [
                    "Dict"
                ],
                "summary": "更新字典条目",
                "responses": {}
            },
            "delete": {
                "tags": [
                    "Dict"
                ],
                "summary": "删除字典条目",
                "responses": {}
            }
        },
        "/api/v1/menus": {
            "post": {
                "tags": [
                    "Menu"
                ],
                "summary": "创建菜单",
                "responses": {}
            }
        },
        "/api/v1/menus/tree": {
            "get": {
                "tags": [
                    "Menu"
                ],
                "summary": "菜单树（导航结构，权限校验在业务接口层）",
                "responses": {}
            }
        },
        "/api/v1/permissions": {
            "get": {
                "tags": [
                    "Role"
                ],
                "summary": "权限列表",
                "responses": {}
            }
        },
        "/api/v1/public/configs": {
            "get": {
                "tags": [
                    "Config"
                ],
                "summary": "公开配置列表",
                "responses": {}
            }
        },
        "/api/v1/public/configs/:key": {
            "get": {
                "tags": [
                    "Config"
                ],
                "summary": "公开配置单条",
                "responses": {}
            }
        },
        "/api/v1/public/dicts/:code/entries": {
            "get": {
                "tags": [
                    "Dict"
                ],
                "summary": "公开字典条目（无需登录）",
                "responses": {}
            }
        },
        "/api/v1/roles": {
            "get": {
                "tags": [
                    "Role"
                ],
                "summary": "角色列表",
                "responses": {}
            }
        },
        "/api/v1/users": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "用户列表",
                "responses": {}
            },
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "创建用户",
                "responses": {}
            }
        },
        "/api/v1/users/{id}": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "获取用户",
                "responses": {}
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Kingfisher Admin API",
	Description:      "后台管理系统 API 文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
